'use strict';
const $=id=>document.getElementById(id);let meta,sid=null,bid=null,automatic=false,generation=0,busy=false,batchTimer=null;
function notice(text,error=false){$('notice').textContent=text;$('notice').style.borderColor=error?'#ee897f':'#66ddbe';}
async function api(path,data){const options=data?{method:'POST',headers:{'Content-Type':'application/json','X-GeoNav-Token':meta.token},body:JSON.stringify(data)}:{};const r=await fetch(path,options);const v=await r.json();if(!r.ok)throw Error(v.error||'请求失败');return v;}
const terminal=s=>['completed','cancelled','failed'].includes(s.status);
function updatePolicies(){const task=meta.tasks.find(t=>t.key===$('task').value);$('policy').replaceChildren(...task.policies.map(x=>{let o=document.createElement('option');o.textContent=x;return o;}));}
function render(s){$('status').textContent={ready:'已初始化',running:'运行中',completed:s.result?.success?'到达目标':'预算耗尽',cancelled:'用户结束',failed:'推理失败'}[s.status];$('steps').textContent=`${s.steps} / ${s.budget}`;$('position').textContent=`(${s.position.join(', ')})`;$('sg').textContent=s.result?`${s.result.sg_m} 米`:terminal(s)?'未完成':'终止后计算';
const done=terminal(s);for(const id of ['step','auto','cancel'])$(id).disabled=done||busy;$('pause').disabled=!automatic;$('export').classList.toggle('disabled',!done);$('export').href=done?`/api/export?id=${s.id}`:'#';
$('target').src=`/api/image?id=${s.id}&cell=target`;$('current').src=`/api/image?id=${s.id}&cell=${s.position[0]*s.grid+s.position[1]}`;
const visited=new Set(s.visited),current=s.position[0]*s.grid+s.position[1],map=$('map');map.style.gridTemplateColumns=`repeat(${s.grid},1fr)`;const cells=[];
for(let i=0;i<s.grid*s.grid;i++){const d=document.createElement('div');d.className='cell'+(visited.has(i)?'':' unknown')+(i===current?' active':'');const label=document.createElement('span');label.textContent=i===current?'◉':String(i);if(visited.has(i)){const im=document.createElement('img');im.src=`/api/image?id=${s.id}&cell=${i}`;im.alt=`已观察图块${i}`;d.append(im);}d.append(label);cells.push(d);}map.replaceChildren(...cells);
const ns='http://www.w3.org/2000/svg',svg=document.createElementNS(ns,'svg');svg.classList.add('path-overlay');svg.setAttribute('viewBox',`0 0 ${s.grid} ${s.grid}`);const path=document.createElementNS(ns,'polyline');path.setAttribute('points',s.trajectory.map(x=>`${x.patch_id%s.grid+.5},${Math.floor(x.patch_id/s.grid)+.5}`).join(' '));path.setAttribute('fill','none');path.setAttribute('stroke','#6efbd0');path.setAttribute('stroke-width','.035');path.setAttribute('stroke-dasharray','.12 .06');svg.append(path);map.append(svg);
const d=s.last_decision;if(d){$('decision').textContent=`动作 ${d.action} · ${d.reason||'探索'}${d.cloud?' · '+(d.cloud.fallback?'API失败→本地回退':'单云端模型'):''}`;$('detail').textContent=JSON.stringify({coverage:d.coverage,local_cue_probabilities:d.probabilities,cloud:d.cloud?{evidence:d.cloud.evidence,error:d.cloud.error,latency_ms:d.cloud.latency_ms,usage:d.cloud.usage}:undefined},null,2);}else{$('decision').textContent='尚未执行决策。';$('detail').textContent='';}if(done){automatic=false;$('pause').disabled=true;notice('运行已终止；可导出新记录，历史实验没有覆盖。');}}
async function step(){if(busy||!sid)return;busy=true;$('step').disabled=true;$('auto').disabled=true;try{const g=generation;const s=await api('/api/step',{id:sid});if(g===generation)render(s);}catch(e){automatic=false;notice(e.message,true);try{render(await api('/api/state?id='+sid));}catch(_){}}finally{busy=false;if(sid){const s=await api('/api/state?id='+sid);render(s);}}}
$('create').onclick=async()=>{if(busy)return;automatic=false;if(sid){const old=await api('/api/state?id='+sid);if(!terminal(old))await api('/api/cancel',{id:sid});}generation++;try{const s=await api('/api/create',{task:$('task').value,policy:$('policy').value,seed:Number($('seed').value)});sid=s.id;render(s);notice('新任务已初始化；目标与当前图已提供。策略每一步实时推理。');}catch(e){notice(e.message,true);}};
$('step').onclick=step;$('auto').onclick=async()=>{automatic=true;const g=generation;$('pause').disabled=false;while(automatic&&g===generation){await step();if(automatic)await new Promise(r=>setTimeout(r,250));}};$('pause').onclick=()=>{automatic=false;$('pause').disabled=true;notice('已暂停自动执行；当前正在处理的一步仍会完成。');};$('cancel').onclick=async()=>{automatic=false;try{render(await api('/api/cancel',{id:sid}));}catch(e){notice(e.message,true);}};
$('save-api').onclick=async()=>{try{const c=await api('/api/config',{base_url:$('base-url').value,model:$('model').value,api_key:$('api-key').value,timeout:Number($('timeout').value),max_tokens:Number($('max-tokens').value)});$('api-key').value='';$('api-status').textContent=`已保存 ${c.model}；Key${c.key_configured?'已配置':'为空'}（不回显）。`;notice('API配置已保存到后端内存；尚未发送模型请求。');}catch(e){notice(e.message,true);}};
function renderBatch(s){$('batch-status').textContent=`${s.status} · ${s.id}`;$('batch-start').disabled=s.status==='running';$('batch-stop').disabled=s.status!=='running';$('batch-export').classList.toggle('disabled',s.status==='running');$('batch-export').href=`/api/batch-export?id=${s.id}`;$('batch-metrics').replaceChildren(...Object.entries(s.metrics).map(([name,m])=>{let a=document.createElement('article');let h=document.createElement('h2');h.textContent=name;let strong=document.createElement('strong');strong.textContent=(m.sr_planned*100).toFixed(1)+'%';let p=document.createElement('p');p.textContent=`SR（计划分母） · 完成${m.completed}/${m.planned}，成功${m.successes}\nSG ${m.sg_m===null?'完整队列未完成':m.sg_m.toFixed(1)+'米'} · API ${m.api_requests}，回退${m.fallback_actions}\nTokens ${m.total_tokens} · 时延${(m.api_latency_ms/1000).toFixed(1)}秒`;p.style.whiteSpace='pre-line';a.append(h,strong,p);return a;}));}
async function pollBatch(){if(!bid)return;try{const s=await api('/api/batch?id='+bid);renderBatch(s);if(s.status==='running')batchTimer=setTimeout(pollBatch,1200);}catch(e){notice(e.message,true);}}
$('batch-start').onclick=async()=>{try{let arms=$('batch-arms').value==='cloud'?['M0','Cloud']:['M0','Coverage3Radial'];const s=await api('/api/batch',{grid:Number($('batch-grid').value),arms,count:Number($('batch-count').value),seed:Number($('seed').value)});bid=s.id;renderBatch(s);pollBatch();notice('批量新队列已启动；按计划分母统计，不覆盖旧结果。');}catch(e){notice(e.message,true);}};$('batch-stop').onclick=async()=>{if(bid)renderBatch(await api('/api/batch-cancel',{id:bid}));};
document.querySelectorAll('.tab').forEach(b=>b.onclick=()=>{document.querySelectorAll('.view').forEach(v=>v.classList.toggle('hidden',v.id!==b.dataset.view));document.querySelectorAll('.tab').forEach(x=>x.classList.toggle('selected',x===b));});
(async()=>{try{meta=await api('/api/meta');$('task').replaceChildren(...meta.tasks.map(t=>{let o=document.createElement('option');o.value=t.key;o.textContent=t.label;return o;}));updatePolicies();$('task').onchange=updatePolicies;if(meta.api){$('base-url').value=meta.api.base_url;$('model').value=meta.api.model;$('api-status').textContent='已读取现有本地配置；Key不回显。';}notice(meta.mode);}catch(e){notice(e.message,true);}})();
